//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class M_AgencyType
    {
        public int AgencyTypeId { get; set; }
        public string Agent_type_code { get; set; }
        public string Agent_type_Name { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string Update_By { get; set; }
        public string Last_Inv_No { get; set; }
        public string Last_TAX_No { get; set; }
        public string Last_Refund_Inv_No { get; set; }
        public string IsActive { get; set; }
    }
}
