//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class M_CNReason
    {
        public M_CNReason()
        {
            this.T_Invoice_CN = new HashSet<T_Invoice_CN>();
        }
    
        public int CNReason_Id { get; set; }
        public string CNReason_Code { get; set; }
        public string CNReason_Name { get; set; }
        public string IsActive { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Update_By { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    
        public virtual ICollection<T_Invoice_CN> T_Invoice_CN { get; set; }
    }
}
