//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class M_Customer_address
    {
        public string cust_addr_id { get; set; }
        public string cust_code { get; set; }
        public string addr_type_code { get; set; }
        public string addr_1 { get; set; }
        public string addr_2 { get; set; }
        public string addr_3 { get; set; }
        public string prvn_name { get; set; }
        public string prvn_code { get; set; }
        public string Cntr_code { get; set; }
        public string zip_code { get; set; }
        public string stts_code { get; set; }
        public Nullable<System.DateTime> crtd_dt { get; set; }
        public string crtd_by { get; set; }
        public Nullable<System.DateTime> last_upd_dt { get; set; }
        public string last_upd_by { get; set; }
    }
}
