//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class M_Employee
    {
        public int UserID { get; set; }
        public string UserCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserGroup { get; set; }
        public string Station_Code { get; set; }
        public string PID { get; set; }
        public string DefaultMenu { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Active { get; set; }
        public string IsActive { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Update_By { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<int> Last_POS_ID { get; set; }
        public string IP_Address { get; set; }
        public Nullable<System.DateTime> LastLogIn_Date { get; set; }
        public Nullable<bool> IsOnline { get; set; }
        public bool IsUserAD { get; set; }
    }
}
