//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class M_FlightFeeGroup
    {
        public M_FlightFeeGroup()
        {
            this.M_FlightFee = new HashSet<M_FlightFee>();
        }
    
        public System.Guid ID { get; set; }
        public string NameTH { get; set; }
        public string NameEN { get; set; }
        public string DescriptionTH { get; set; }
        public string DescriptionEN { get; set; }
    
        public virtual ICollection<M_FlightFee> M_FlightFee { get; set; }
    }
}
