//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class M_POS_Machine
    {
        public M_POS_Machine()
        {
            this.T_ABB = new HashSet<T_ABB>();
        }
    
        public int POS_Id { get; set; }
        public string POS_Code { get; set; }
        public string POS_MacNo { get; set; }
        public string Station_Code { get; set; }
        public string SlipMessage_Code { get; set; }
        public string SetEJ { get; set; }
        public string CusDisplay { get; set; }
        public string CashDrawer { get; set; }
        public string FormatPrint { get; set; }
        public string Last_Inv_No { get; set; }
        public string Last_TAX_No { get; set; }
        public string Last_Refund_Inv_No { get; set; }
        public string Active { get; set; }
        public string IsActive { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Update_By { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string Last_AK_No { get; set; }
        public string Last_QZ_No { get; set; }
    
        public virtual ICollection<T_ABB> T_ABB { get; set; }
    }
}
