//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class M_SlipMessageDetails
    {
        public int ID { get; set; }
        public Nullable<int> SlipMessage_Id { get; set; }
        public string Descriptions { get; set; }
        public Nullable<int> SortID { get; set; }
        public Nullable<bool> SlipStat { get; set; }
        public string Active { get; set; }
    }
}
