//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class M_Station
    {
        public int Station_Id { get; set; }
        public string Station_Code { get; set; }
        public string Station_Name { get; set; }
        public string Active { get; set; }
        public string IsActive { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Update_By { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string Location_Name { get; set; }
        public Nullable<int> ABB_SlipMessage_Id { get; set; }
        public Nullable<int> INV_SlipMessage_Id { get; set; }
        public Nullable<int> CN_SlipMessage_Id { get; set; }
        public Nullable<bool> ABB_Print_A4 { get; set; }
        public Nullable<bool> INV_Print_A4 { get; set; }
        public Nullable<bool> CN_Print_A4 { get; set; }
    }
}
