//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class M_UserGroupMenu
    {
        public int RowId { get; set; }
        public string UserGroupCode { get; set; }
        public string Menu_Code { get; set; }
        public Nullable<int> CanView { get; set; }
        public Nullable<int> CanInsert { get; set; }
        public Nullable<int> CanDelete { get; set; }
        public Nullable<int> CanUpdate { get; set; }
        public Nullable<int> CanProcess { get; set; }
        public Nullable<int> CanPrint { get; set; }
    }
}
