//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class M_VAT
    {
        public string VAT_CODE { get; set; }
        public string VAT_NAME { get; set; }
        public Nullable<decimal> VAT_VALUE { get; set; }
        public Nullable<bool> ISACTIVE { get; set; }
    }
}
