//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class rpt
    {
        public int ID { get; set; }
        public Nullable<int> POS_Id { get; set; }
        public Nullable<System.DateTime> Paydate { get; set; }
        public Nullable<int> AmtBill { get; set; }
        public Nullable<decimal> BVat0 { get; set; }
        public Nullable<decimal> BVat7 { get; set; }
        public Nullable<decimal> AVat7 { get; set; }
        public Nullable<decimal> AirPay { get; set; }
        public Nullable<decimal> PayPrice { get; set; }
        public Nullable<decimal> Dec_Inc { get; set; }
    }
}
