//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_ABB
    {
        public System.Guid ABBTid { get; set; }
        public System.Guid TransactionId { get; set; }
        public string PNR_No { get; set; }
        public string TaxInvoiceNo { get; set; }
        public int PAXCountADT { get; set; }
        public int PAXCountCHD { get; set; }
        public decimal ADMINFEE { get; set; }
        public decimal Fuel { get; set; }
        public decimal Service { get; set; }
        public decimal OTHER { get; set; }
        public decimal VAT { get; set; }
        public decimal AIRPORTTAX { get; set; }
        public decimal INSURANCE { get; set; }
        public decimal REP { get; set; }
        public decimal TOTAL { get; set; }
        public decimal ExchangeRateTH { get; set; }
        public int PrintCount { get; set; }
        public string STATUS_INV { get; set; }
        public string Create_By { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Update_By { get; set; }
        public System.DateTime Update_Date { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.Guid> INV_ID { get; set; }
        public Nullable<int> POS_Id { get; set; }
        public string Flight_Code { get; set; }
        public string Flight_Desc { get; set; }
        public string Passenger_Name { get; set; }
        public decimal ADMINFEE_Ori { get; set; }
        public decimal Fuel_Ori { get; set; }
        public decimal Service_Ori { get; set; }
        public decimal OTHER_Ori { get; set; }
        public decimal VAT_Ori { get; set; }
        public decimal AIRPORTTAX_Ori { get; set; }
        public decimal INSURANCE_Ori { get; set; }
        public decimal REP_Ori { get; set; }
        public decimal TOTAL_Ori { get; set; }
        public decimal Discount_Ori { get; set; }
    
        public virtual M_POS_Machine M_POS_Machine { get; set; }
        public virtual T_Invoice_Info T_Invoice_Info { get; set; }
    }
}
