//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_Invoice_Manual
    {
        public System.Guid TransactionId { get; set; }
        public string Receipt_no { get; set; }
        public string Receipt_type { get; set; }
        public Nullable<System.DateTime> Receipt_date { get; set; }
        public string Station_Code { get; set; }
        public string SlipMessage_Code { get; set; }
        public string Branch_name { get; set; }
        public string Branch_address1 { get; set; }
        public string Branch_address2 { get; set; }
        public string Branch_address3 { get; set; }
        public string Branch_Tax_ID { get; set; }
        public string POS_Code { get; set; }
        public string Cashier_no { get; set; }
        public string Booking_name { get; set; }
        public string Booking_no { get; set; }
        public Nullable<System.DateTime> Booking_date { get; set; }
        public string Customer_address1 { get; set; }
        public string Customer_address2 { get; set; }
        public string Customer_address3 { get; set; }
        public string Customer_Tax_ID { get; set; }
        public string Passenger_name { get; set; }
        public string Route { get; set; }
        public string Remark { get; set; }
        public string Create_by { get; set; }
        public string Update_by { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string VAT_CODE { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> Net_balance { get; set; }
        public string Payment_type { get; set; }
        public string Card_no { get; set; }
        public string Bank { get; set; }
        public string Document_State { get; set; }
        public Nullable<bool> IsPrint { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.Guid> CN_ID { get; set; }
        public string Status { get; set; }
        public string SlipHeader { get; set; }
    }
}
