//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_Invoice_Detail
    {
        public int ID { get; set; }
        public string Receipt_no { get; set; }
        public string Flight_Fee_Code { get; set; }
        public string Flight_Fee_Name { get; set; }
        public string Other { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> UnitQTY { get; set; }
        public Nullable<decimal> AmountTH { get; set; }
    }
}
