//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_Invoice_Fare
    {
        public System.Guid ID { get; set; }
        public System.Guid INV_ID { get; set; }
        public string Pax_Type { get; set; }
        public string ChargeCode { get; set; }
        public int Quantity { get; set; }
        public string Currency { get; set; }
        public decimal Amount { get; set; }
        public decimal ExchangeRateTH { get; set; }
        public decimal DiscountTH { get; set; }
        public decimal AmountTH { get; set; }
        public decimal TotalTH { get; set; }
        public string Group { get; set; }
        public Nullable<System.Guid> Flight_ID { get; set; }
    
        public virtual T_Invoice_Info T_Invoice_Info { get; set; }
        public virtual T_Invoice_Flight T_Invoice_Flight { get; set; }
    }
}
