//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_Invoice_Info
    {
        public T_Invoice_Info()
        {
            this.T_ABB = new HashSet<T_ABB>();
            this.T_Invoice_Fare = new HashSet<T_Invoice_Fare>();
            this.T_Invoice_Fee = new HashSet<T_Invoice_Fee>();
            this.T_Invoice_Flight = new HashSet<T_Invoice_Flight>();
            this.T_Invoice_Payment = new HashSet<T_Invoice_Payment>();
        }
    
        public System.Guid TransactionId { get; set; }
        public string INV_No { get; set; }
        public string Ref_INV_No { get; set; }
        public Nullable<System.DateTime> INVDate { get; set; }
        public string Receipt_By { get; set; }
        public Nullable<System.DateTime> Receipt_Date { get; set; }
        public string Booking_No { get; set; }
        public Nullable<System.DateTime> Booking_Date { get; set; }
        public Nullable<int> PayType { get; set; }
        public string BankName { get; set; }
        public string BranchNo { get; set; }
        public string AcountNo { get; set; }
        public string Cheque_No { get; set; }
        public Nullable<System.DateTime> Cheque_Date { get; set; }
        public Nullable<int> INVType { get; set; }
        public string Remark { get; set; }
        public Nullable<int> VatType { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string UpDate_By { get; set; }
        public string Address { get; set; }
        public string POS_Code { get; set; }
        public string SlipMessage_Code { get; set; }
        public bool IsPrint { get; set; }
        public Nullable<System.Guid> CN_ID { get; set; }
        public bool IsCancel { get; set; }
        public Nullable<System.DateTime> Cancel_Date { get; set; }
        public string OR_Reason { get; set; }
        public string Status { get; set; }
        public System.Guid INV_ID { get; set; }
        public string ABB_NO { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public int PAXCountADT { get; set; }
        public int PAXCountCHD { get; set; }
        public decimal ADMINFEE { get; set; }
        public decimal Fuel { get; set; }
        public decimal Service { get; set; }
        public decimal OTHER { get; set; }
        public decimal VAT { get; set; }
        public decimal AIRPORTTAX { get; set; }
        public decimal INSURANCE { get; set; }
        public decimal REP { get; set; }
        public decimal Discount { get; set; }
        public decimal TOTAL { get; set; }
        public decimal ExchangeRateTH { get; set; }
        public decimal ADMINFEE_Ori { get; set; }
        public decimal Fuel_Ori { get; set; }
        public decimal Service_Ori { get; set; }
        public decimal OTHER_Ori { get; set; }
        public decimal VAT_Ori { get; set; }
        public decimal AIRPORTTAX_Ori { get; set; }
        public decimal INSURANCE_Ori { get; set; }
        public decimal REP_Ori { get; set; }
        public decimal Discount_Ori { get; set; }
        public decimal TOTAL_Ori { get; set; }
        public string PassengerName { get; set; }
    
        public virtual M_Customer M_Customer { get; set; }
        public virtual M_PaymentType M_PaymentType { get; set; }
        public virtual ICollection<T_ABB> T_ABB { get; set; }
        public virtual T_Invoice_CN T_Invoice_CN { get; set; }
        public virtual ICollection<T_Invoice_Fare> T_Invoice_Fare { get; set; }
        public virtual ICollection<T_Invoice_Fee> T_Invoice_Fee { get; set; }
        public virtual ICollection<T_Invoice_Flight> T_Invoice_Flight { get; set; }
        public virtual ICollection<T_Invoice_Payment> T_Invoice_Payment { get; set; }
    }
}
