//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_Invoice_Payment
    {
        public System.Guid ID { get; set; }
        public System.Guid INV_ID { get; set; }
        public int SEQ { get; set; }
        public string PaymentMethodCode { get; set; }
        public string PaymentType_Name { get; set; }
        public string CurrencyCode { get; set; }
        public decimal ExchangeRateTH { get; set; }
        public decimal PaymentAmount_Ori { get; set; }
        public decimal PaymentAmount { get; set; }
        public System.DateTime ApprovalDate { get; set; }
        public string AgentCode { get; set; }
    
        public virtual T_Invoice_Info T_Invoice_Info { get; set; }
    }
}
