//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_Invoice_Flight
    {
        public T_Invoice_Flight()
        {
            this.T_Invoice_Fare = new HashSet<T_Invoice_Fare>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid INV_ID { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public System.DateTime ArraivalDate { get; set; }
        public string DepartureStation { get; set; }
        public string ArrivalStation { get; set; }
        public string CarrierCode { get; set; }
        public string FlightNumber { get; set; }
        public int SEQ { get; set; }
    
        public virtual T_Invoice_Info T_Invoice_Info { get; set; }
        public virtual ICollection<T_Invoice_Fare> T_Invoice_Fare { get; set; }
    }
}
