//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_Invoice_Seq
    {
        public int Seq_ID { get; set; }
        public string Prefix { get; set; }
        public string Last_Sequence { get; set; }
        public Nullable<long> Seq_Number { get; set; }
        public string Curr_Month { get; set; }
        public string Curr_Year { get; set; }
        public string Next_Sequence { get; set; }
        public string Last_POS_Code { get; set; }
        public string Last_Station_Code { get; set; }
        public Nullable<System.DateTime> Last_Modify_date { get; set; }
        public string Last_Update_by { get; set; }
    }
}
