//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_LogBookingCurrentUpdate
    {
        public System.Guid LogID { get; set; }
        public System.Guid TransactionId { get; set; }
        public string PNR_No { get; set; }
        public string Method { get; set; }
        public string FormName { get; set; }
        public string Msg { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string INV_No { get; set; }
        public string ABBNo { get; set; }
        public string TableName { get; set; }
        public string ColName { get; set; }
        public string ValueOld { get; set; }
        public string ValueNew { get; set; }
    }
}
