//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateInvoiceSystem
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class T_PassengerFeeServiceChargeNewItem
    {
        public System.Guid PassengerFeeServiceChargeTId { get; set; }
        public System.Guid PassengerFeeTId { get; set; }
        public Nullable<long> PassengerId { get; set; }
        public Nullable<long> PassengerFeeNo { get; set; }
        public Nullable<System.DateTime> FeeCreateDate { get; set; }
        public string ServiceChargeNo { get; set; }
        public string ChargeType { get; set; }
        public string CollectType { get; set; }
        public string ChargeCode { get; set; }
        public string TicketCode { get; set; }
        public string BaseCurrencyCode { get; set; }
        public string CurrencyCode { get; set; }
        public decimal Amount { get; set; }
        public decimal BaseAmount { get; set; }
        public string ChargeDetail { get; set; }
        public string ForeignCurrencyCode { get; set; }
        public decimal ForeignAmount { get; set; }
        public string Create_By { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Update_By { get; set; }
        public System.DateTime Update_Date { get; set; }
    }
}
